import { Connector } from '../../../core/Connector.js';
import type {
  OpenAIRealtimeClientSecret,
  OpenAIRealtimeSessionConfig,
  OpenAIRealtimeTranscriptionSessionConfig,
  OpenAIRealtimeTranslationClientSessionConfig,
} from './RealtimeTypes.js';
import { assertOpenAIRealtimePCMRates } from './RealtimeTypes.js';

export interface CreateRealtimeClientSecretOptions {
  session: OpenAIRealtimeSessionConfig | OpenAIRealtimeTranscriptionSessionConfig;
  expiresAfterSeconds?: number;
  safetyIdentifier?: string;
}

export interface CreateRealtimeTranslationClientSecretOptions {
  session: OpenAIRealtimeTranslationClientSessionConfig;
  safetyIdentifier?: string;
}

export interface CreateRealtimeWebRTCCallOptions {
  /** SDP offer generated by RTCPeerConnection.createOffer(). */
  sdp: string;
  /** Optional initial session configuration sent atomically with the offer. */
  session?: OpenAIRealtimeSessionConfig;
  safetyIdentifier?: string;
}

/** REST helpers for browser/WebRTC credentials and server-side SIP call control. */
export class OpenAIRealtimeAPI {
  readonly connector: Connector;

  constructor(connector: string | Connector) {
    this.connector = typeof connector === 'string' ? Connector.get(connector) : connector;
  }

  async createClientSecret(options: CreateRealtimeClientSecretOptions): Promise<OpenAIRealtimeClientSecret> {
    assertOpenAIRealtimePCMRates(options.session);
    if (options.expiresAfterSeconds !== undefined
      && (options.expiresAfterSeconds < 10 || options.expiresAfterSeconds > 7200)) {
      throw new RangeError('expiresAfterSeconds must be between 10 and 7200');
    }
    return this.request('/realtime/client_secrets', {
      session: options.session,
      ...(options.expiresAfterSeconds === undefined ? {} : {
        expires_after: { anchor: 'created_at', seconds: options.expiresAfterSeconds },
      }),
    }, options.safetyIdentifier) as Promise<OpenAIRealtimeClientSecret>;
  }

  async createTranslationClientSecret(
    options: CreateRealtimeTranslationClientSecretOptions,
  ): Promise<OpenAIRealtimeClientSecret> {
    return this.request('/realtime/translations/client_secrets', {
      session: options.session,
    }, options.safetyIdentifier) as Promise<OpenAIRealtimeClientSecret>;
  }

  /** Exchange a WebRTC SDP offer for OpenAI's SDP answer. */
  async createWebRTCCall(options: CreateRealtimeWebRTCCallOptions): Promise<string> {
    if (!options.sdp.trim()) throw new RangeError('sdp must not be empty');
    if (options.session) assertOpenAIRealtimePCMRates(options.session);
    return this.request('/realtime/calls', {
      sdp: options.sdp,
      ...(options.session ? { session: { ...options.session, type: 'realtime' } } : {}),
    }, options.safetyIdentifier, 'text') as Promise<string>;
  }

  async acceptCall(callId: string, session: OpenAIRealtimeSessionConfig): Promise<void> {
    assertOpenAIRealtimePCMRates(session);
    await this.request(`/realtime/calls/${encodeURIComponent(callId)}/accept`, {
      ...session,
      type: 'realtime',
    });
  }

  async rejectCall(callId: string, statusCode?: number): Promise<void> {
    await this.request(`/realtime/calls/${encodeURIComponent(callId)}/reject`,
      statusCode === undefined ? {} : { status_code: statusCode });
  }

  async hangupCall(callId: string): Promise<void> {
    await this.request(`/realtime/calls/${encodeURIComponent(callId)}/hangup`);
  }

  async referCall(callId: string, targetUri: string): Promise<void> {
    await this.request(`/realtime/calls/${encodeURIComponent(callId)}/refer`, { target_uri: targetUri });
  }

  private async request(
    path: string,
    body?: Record<string, unknown>,
    safetyIdentifier?: string,
    responseType: 'json' | 'text' = 'json',
  ): Promise<unknown> {
    const base = this.connector.baseURL || 'https://api.openai.com/v1';
    const url = `${base.replace(/\/$/, '')}/${path.replace(/^\//, '')}`;
    const response = await this.connector.fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(safetyIdentifier ? { 'OpenAI-Safety-Identifier': safetyIdentifier } : {}),
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    if (!response.ok) {
      const detail = await response.text();
      throw new Error(`OpenAI Realtime API ${response.status}: ${detail || response.statusText}`);
    }
    if (response.status === 204) return undefined;
    const text = await response.text();
    if (responseType === 'text') return text;
    return text ? JSON.parse(text) : undefined;
  }
}
