/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-tool-registry.ts
 *
 * To regenerate: npm run generate:tools
 */

import type { ToolFunction } from '../domain/entities/Tool.js';

import { executeJavaScript } from './code/executeJavaScript.js';
import { customToolDelete } from './custom-tools/customToolDelete.js';
import { customToolDraft } from './custom-tools/customToolDraft.js';
import { customToolList } from './custom-tools/customToolList.js';
import { customToolLoad } from './custom-tools/customToolLoad.js';
import { customToolSave } from './custom-tools/customToolSave.js';
import { customToolTest } from './custom-tools/customToolTest.js';
import { desktopGetCursor } from './desktop/getCursor.js';
import { desktopGetScreenSize } from './desktop/getScreenSize.js';
import { desktopKeyboardKey } from './desktop/keyboardKey.js';
import { desktopKeyboardType } from './desktop/keyboardType.js';
import { desktopMouseClick } from './desktop/mouseClick.js';
import { desktopMouseDrag } from './desktop/mouseDrag.js';
import { desktopMouseMove } from './desktop/mouseMove.js';
import { desktopMouseScroll } from './desktop/mouseScroll.js';
import { desktopScreenshot } from './desktop/screenshot.js';
import { desktopWindowFocus } from './desktop/windowFocus.js';
import { desktopWindowList } from './desktop/windowList.js';
import { editFile } from './filesystem/editFile.js';
import { glob } from './filesystem/glob.js';
import { grep } from './filesystem/grep.js';
import { listDirectory } from './filesystem/listDirectory.js';
import { readFile } from './filesystem/readFile.js';
import { writeFile } from './filesystem/writeFile.js';
import { jsonManipulator } from './json/jsonManipulator.js';
import { generateRoutine } from './routines/generateRoutine.js';
import { routineDelete } from './routines/routineDelete.js';
import { routineGet } from './routines/routineGet.js';
import { routineGetTaskSteps } from './routines/routineGetTaskSteps.js';
import { routineList } from './routines/routineList.js';
import { routineListExecutions } from './routines/routineListExecutions.js';
import { routineUpdate } from './routines/routineUpdate.js';
import { routineUpdateTask } from './routines/routineUpdateTask.js';
import { bash } from './shell/bash.js';
import { bgProcessKill } from './shell/bgProcessKill.js';
import { bgProcessList } from './shell/bgProcessList.js';
import { bgProcessOutput } from './shell/bgProcessOutput.js';
import { devServer } from './shell/devServer.js';
import { webFetch } from './web/webFetch.js';

/** Tool category for grouping */
export type ToolCategory = 'filesystem' | 'shell' | 'web' | 'code' | 'json' | 'connector' | 'desktop' | 'custom-tools' | 'routines' | 'other';

/** Metadata for a tool in the registry */
export interface ToolRegistryEntry {
  /** Tool name (matches definition.function.name) */
  name: string;
  /** Export variable name */
  exportName: string;
  /** Human-readable display name */
  displayName: string;
  /** Category for grouping */
  category: ToolCategory;
  /** Brief description */
  description: string;
  /** The actual tool function */
  tool: ToolFunction;
  /** Whether this tool is safe without explicit approval */
  safeByDefault: boolean;
  /** SHA-256 fingerprint of the tool source and its OneRingAI runtime source. */
  implementationHash?: string;
  /** Whether this tool requires a connector */
  requiresConnector?: boolean;
  /** Supported connector service types (if requiresConnector) */
  connectorServiceTypes?: string[];
}

/** Complete registry of all built-in tools */
export const toolRegistry: ToolRegistryEntry[] = [
  {
    name: 'execute_javascript',
    exportName: 'executeJavaScript',
    displayName: 'Execute Javascript',
    category: 'code',
    description: "Execute JavaScript code in a secure sandbox with authenticated API access via connectors.",
    tool: executeJavaScript,
    safeByDefault: false,
    implementationHash: 'sha256:0a24203ba7685483a2853ab3fd123241514371ca31d6ba2a43d9148bf674aae3',
  },
  {
    name: 'custom_tool_delete',
    exportName: 'customToolDelete',
    displayName: 'Custom Tool Delete',
    category: 'custom-tools',
    description: "Delete a custom tool from persistent storage.",
    tool: customToolDelete,
    safeByDefault: false,
    implementationHash: 'sha256:40cbe959fefb002c7b9be398407d526ccb017773b5f19867c16852d422d136a0',
  },
  {
    name: 'custom_tool_draft',
    exportName: 'customToolDraft',
    displayName: 'Custom Tool Draft',
    category: 'custom-tools',
    description: "Validate a draft custom tool definition. Checks name format, schema structure, and code syntax.",
    tool: customToolDraft,
    safeByDefault: true,
    implementationHash: 'sha256:42ef251558bf81222af056ea41164b54d579ab985079d234fa79b75cc7dcd809',
  },
  {
    name: 'custom_tool_list',
    exportName: 'customToolList',
    displayName: 'Custom Tool List',
    category: 'custom-tools',
    description: "List saved custom tools from persistent storage. Supports filtering by search text, tags, and category.",
    tool: customToolList,
    safeByDefault: true,
    implementationHash: 'sha256:7d71aa8f8b2bce95959f7a137bfc9029e671c91edd70630af89db6a216c0b1c4',
  },
  {
    name: 'custom_tool_load',
    exportName: 'customToolLoad',
    displayName: 'Custom Tool Load',
    category: 'custom-tools',
    description: "Load a full custom tool definition from storage (including code).",
    tool: customToolLoad,
    safeByDefault: true,
    implementationHash: 'sha256:3a1ed294cc6b1e0a33fa34920d77c15f8b26d656acad7e38771f69892e443079',
  },
  {
    name: 'custom_tool_save',
    exportName: 'customToolSave',
    displayName: 'Custom Tool Save',
    category: 'custom-tools',
    description: "Save a custom tool definition to persistent storage.",
    tool: customToolSave,
    safeByDefault: false,
    implementationHash: 'sha256:9312eab9568ec5e13884f1c2966e682f27f6ca951a9e481ec0978bfa71386294',
  },
  {
    name: 'custom_tool_test',
    exportName: 'customToolTest',
    displayName: 'Custom Tool Test',
    category: 'custom-tools',
    description: "Test custom tool code by executing it in the VM sandbox with provided test input.",
    tool: customToolTest,
    safeByDefault: false,
    implementationHash: 'sha256:c13e920f34c852c34956e333636c019785aa2087f38e5e5699812c4096a2e342',
  },
  {
    name: 'desktop_get_cursor',
    exportName: 'desktopGetCursor',
    displayName: 'Desktop Get Cursor',
    category: 'desktop',
    description: "Get the current mouse cursor position in screen pixel coordinates (same space as the screenshot and mouseClick/mouseMove).",
    tool: desktopGetCursor,
    safeByDefault: false,
    implementationHash: 'sha256:24754890bf9b0f46ac17e02d9c8d5ea27c2e9fd5a4b17a758574f66ec1716464',
  },
  {
    name: 'desktop_get_screen_size',
    exportName: 'desktopGetScreenSize',
    displayName: 'Desktop Get Screen Size',
    category: 'desktop',
    description: "Get the screen dimensions. Returns physical pixel size (screenshot space), logical size (OS coordinates), and the scale factor (e.g., 2.0 on Retina displays). All desktop tool coordinates use physical",
    tool: desktopGetScreenSize,
    safeByDefault: false,
    implementationHash: 'sha256:f0097a90d2987f64348303421d17e33e6c98f122580a432315f424b232f5bdc7',
  },
  {
    name: 'desktop_keyboard_key',
    exportName: 'desktopKeyboardKey',
    displayName: 'Desktop Keyboard Key',
    category: 'desktop',
    description: "Press a keyboard shortcut or special key. Use \"+\" to combine keys (e.g., \"ctrl+c\", \"cmd+shift+s\", \"enter\", \"tab\", \"escape\"). Modifiers: ctrl, cmd/command, alt/option, shift. Special keys: enter, tab, ",
    tool: desktopKeyboardKey,
    safeByDefault: false,
    implementationHash: 'sha256:c84c6bad2c5d82e04ed2bcbd8ed26f735809d815e6bd17a45b620ee23fa72062',
  },
  {
    name: 'desktop_keyboard_type',
    exportName: 'desktopKeyboardType',
    displayName: 'Desktop Keyboard Type',
    category: 'desktop',
    description: "Type text using the keyboard. Each character is typed as a keypress. Use this for entering text into focused input fields.",
    tool: desktopKeyboardType,
    safeByDefault: false,
    implementationHash: 'sha256:b4e7de323350deb2d667c2d1f781d2f825179f39fcc3314f0ca347133a253eae',
  },
  {
    name: 'desktop_mouse_click',
    exportName: 'desktopMouseClick',
    displayName: 'Desktop Mouse Click',
    category: 'desktop',
    description: "Click the mouse at the specified position or at the current cursor position. Supports left/right/middle button and single/double/triple click.",
    tool: desktopMouseClick,
    safeByDefault: false,
    implementationHash: 'sha256:fa51618fd63360eae3694136a6e9891e530a2088686c3fe17caa479b3054bc38',
  },
  {
    name: 'desktop_mouse_drag',
    exportName: 'desktopMouseDrag',
    displayName: 'Desktop Mouse Drag',
    category: 'desktop',
    description: "Drag the mouse from one position to another. Presses the button at the start position, moves to the end position, then releases.",
    tool: desktopMouseDrag,
    safeByDefault: false,
    implementationHash: 'sha256:1e517e27e17213b8a3783b1aed944c6e417f8a14065bd25b03698835f580fe73',
  },
  {
    name: 'desktop_mouse_move',
    exportName: 'desktopMouseMove',
    displayName: 'Desktop Mouse Move',
    category: 'desktop',
    description: "Move the mouse cursor to the specified (x, y) position. Coordinates are in screen pixel space (full screen). Returns the actual cursor position after the move for verification.",
    tool: desktopMouseMove,
    safeByDefault: false,
    implementationHash: 'sha256:219dd10204b889e7dcf101f94df56c3b05a3a0b9b0f8266093465b86c53488c8',
  },
  {
    name: 'desktop_mouse_scroll',
    exportName: 'desktopMouseScroll',
    displayName: 'Desktop Mouse Scroll',
    category: 'desktop',
    description: "Scroll the mouse wheel. Positive deltaY scrolls down, negative scrolls up. Positive deltaX scrolls right, negative scrolls left. Optionally specify position to scroll at.",
    tool: desktopMouseScroll,
    safeByDefault: false,
    implementationHash: 'sha256:d794af0c8695a67573d52a6e69bd9f7219e131c36c16acc0274be1d9532888fa',
  },
  {
    name: 'desktop_screenshot',
    exportName: 'desktopScreenshot',
    displayName: 'Desktop Screenshot',
    category: 'desktop',
    description: "Take a screenshot of the entire screen or a specific region. Returns the screenshot image for visual analysis. The image pixel coordinates match the coordinate space used by desktop_mouse_click / desk",
    tool: desktopScreenshot,
    safeByDefault: false,
    implementationHash: 'sha256:45621487710382f5670dae1adf1e3f6eda2ea019d9dc4e3772a3f371ff6a1712',
  },
  {
    name: 'desktop_window_focus',
    exportName: 'desktopWindowFocus',
    displayName: 'Desktop Window Focus',
    category: 'desktop',
    description: "Focus (bring to front) a window by its ID. Use desktop_window_list to get available window IDs.",
    tool: desktopWindowFocus,
    safeByDefault: false,
    implementationHash: 'sha256:9516e672e4e8c8a34dabcd8e6dd0eb60d45ca3a4aa59e1b6772470093ec6fee1',
  },
  {
    name: 'desktop_window_list',
    exportName: 'desktopWindowList',
    displayName: 'Desktop Window List',
    category: 'desktop',
    description: "List all visible windows on the desktop. Returns window IDs, titles, application names, and bounds. Use the window ID with desktop_window_focus to bring a window to the foreground.",
    tool: desktopWindowList,
    safeByDefault: false,
    implementationHash: 'sha256:d78fe380327ffbe6be9f62d27a2a37f159768b679337f2e6856fbb60e11b3594',
  },
  {
    name: 'edit_file',
    exportName: 'editFile',
    displayName: 'Edit File',
    category: 'filesystem',
    description: "Perform exact string replacements in files.",
    tool: editFile,
    safeByDefault: false,
    implementationHash: 'sha256:3a692c17e4f60b83fa00950cb73a501f9e40336f1e1ef4226bcea1c79f10019d',
  },
  {
    name: 'glob',
    exportName: 'glob',
    displayName: 'Glob',
    category: 'filesystem',
    description: "Fast file pattern matching tool that finds files by name patterns.",
    tool: glob,
    safeByDefault: true,
    implementationHash: 'sha256:3294edb08f1c2aa445d04481115fb05405a3b5fcaac4756da19aafb5ae13570c',
  },
  {
    name: 'grep',
    exportName: 'grep',
    displayName: 'Grep',
    category: 'filesystem',
    description: "A powerful search tool for finding content within files.",
    tool: grep,
    safeByDefault: true,
    implementationHash: 'sha256:1e91cf43b834722b638f9bb3c6806797258588354d4d030be254da7bbc1a7815',
  },
  {
    name: 'list_directory',
    exportName: 'listDirectory',
    displayName: 'List Directory',
    category: 'filesystem',
    description: "List the contents of a directory on the local filesystem.",
    tool: listDirectory,
    safeByDefault: true,
    implementationHash: 'sha256:f1d78915e0f29ebb69748170733936f965daa76946d1d93232c255b029612841',
  },
  {
    name: 'read_file',
    exportName: 'readFile',
    displayName: 'Read File',
    category: 'filesystem',
    description: "Read content from a file on the local filesystem. Supports text files AND binary document formats — PDF, DOCX, PPTX, XLSX, ODS, ODT, ODP, and images (PNG, JPG, GIF, WEBP) are automatically converted t",
    tool: readFile,
    safeByDefault: true,
    implementationHash: 'sha256:971e171c5fbf93d8cc6c759940886374b90c8b9d343f42f73d17675178a0f5f7',
  },
  {
    name: 'write_file',
    exportName: 'writeFile',
    displayName: 'Write File',
    category: 'filesystem',
    description: "Write content to a file on the local filesystem.",
    tool: writeFile,
    safeByDefault: false,
    implementationHash: 'sha256:9a0984175d7182b339077482dd60bbbc5246ca53f610a456c02755f507883210',
  },
  {
    name: 'json_manipulate',
    exportName: 'jsonManipulator',
    displayName: 'Json Manipulate',
    category: 'json',
    description: "Manipulate JSON objects by deleting, adding, or replacing fields at any depth.",
    tool: jsonManipulator,
    safeByDefault: true,
    implementationHash: 'sha256:87892d826dbec8d4766bbe5702252525e9c619643105c12ceb45f5534c296731',
  },
  {
    name: 'generate_routine',
    exportName: 'generateRoutine',
    displayName: 'Generate Routine',
    category: 'routines',
    description: "Complete routine definition input",
    tool: generateRoutine,
    safeByDefault: false,
    implementationHash: 'sha256:c3d0b9cccc53fcfb0c6de39dfd82818b63832933dbf4678ed91597a4fbc339ee',
  },
  {
    name: 'routine_delete',
    exportName: 'routineDelete',
    displayName: 'Routine Delete',
    category: 'routines',
    description: "Permanently delete a routine definition. Past execution records are preserved, but any schedules or systems still referencing this routine ID will fail at runtime. Confirm with the user before calling",
    tool: routineDelete,
    safeByDefault: false,
    implementationHash: 'sha256:2f728793859c844846bc6b4559d965ad3081339535a7fdc271bb4968e3c72740',
  },
  {
    name: 'routine_get',
    exportName: 'routineGet',
    displayName: 'Routine Get',
    category: 'routines',
    description: "Retrieve a routine definition by ID or by name search. Returns the full routine structure including tasks, parameters, and metadata.",
    tool: routineGet,
    safeByDefault: false,
    implementationHash: 'sha256:7532a9ff6045d9240d812782d3b7719d4e82b4254b4485e7ed37751a60ff4a87',
  },
  {
    name: 'routine_get_task_steps',
    exportName: 'routineGetTaskSteps',
    displayName: 'Routine Get Task Steps',
    category: 'routines',
    description: "Get step-level execution detail for a routine execution. Filter by task name, phase, or step types.\\n\\n",
    tool: routineGetTaskSteps,
    safeByDefault: false,
    implementationHash: 'sha256:42c82b1452fddc38ab1875d5d103b54dc6884dd8c3424f3fb971a419b214cf50',
  },
  {
    name: 'routine_list',
    exportName: 'routineList',
    displayName: 'Routine List',
    category: 'routines',
    description: "List routine definitions accessible to the caller. Returns slim summary entries (id, name, description, version, author, tags, task count, parameter names) — fetch the full structure with routine_get.",
    tool: routineList,
    safeByDefault: false,
    implementationHash: 'sha256:6e593417106d4c95c2fe6bc0a5c50d5153df2ecc1c19c4ceaec4a1b4631895a4',
  },
  {
    name: 'routine_list_executions',
    exportName: 'routineListExecutions',
    displayName: 'Routine List Executions',
    category: 'routines',
    description: "List execution records for a routine. Returns summaries of past and current executions including status, timing, and per-task results.",
    tool: routineListExecutions,
    safeByDefault: false,
    implementationHash: 'sha256:9ac51216c2e5f7edcc70d85defaa10beb3bd2ae4aef25f13729709a3e0df06cc',
  },
  {
    name: 'routine_update',
    exportName: 'routineUpdate',
    displayName: 'Routine Update',
    category: 'routines',
    description: "Update an existing routine definition.",
    tool: routineUpdate,
    safeByDefault: false,
    implementationHash: 'sha256:6ea7630d4ff5e3b1464f6b63e5be531c85a056f76abffbce062d344c7b7ab4f9',
  },
  {
    name: 'routine_update_task',
    exportName: 'routineUpdateTask',
    displayName: 'Routine Update Task',
    category: 'routines',
    description: "Update a specific task within an existing routine definition. Validates the updated routine before saving.",
    tool: routineUpdateTask,
    safeByDefault: false,
    implementationHash: 'sha256:89f35d484b4a08245311a13c3da8cd7ecb4ad99410daa9890985b9c2ca7075f1',
  },
  {
    name: 'bash',
    exportName: 'bash',
    displayName: 'Bash',
    category: 'shell',
    description: "Execute shell commands with optional timeout.",
    tool: bash,
    safeByDefault: false,
    implementationHash: 'sha256:a1a5bbd22aaeb23db8d27a7faacf550e7198679d15f4f7433ef65c5883af53d2',
  },
  {
    name: 'bg_process_kill',
    exportName: 'bgProcessKill',
    displayName: 'Bg Process Kill',
    category: 'shell',
    description: "Stop a running background process. Sends SIGTERM for graceful shutdown (allows the process to clean up), then SIGKILL after 3 seconds if it hasn't exited. Kills the entire process tree — so \"npm run d",
    tool: bgProcessKill,
    safeByDefault: false,
    implementationHash: 'sha256:46021f2e0d5e03f563c8de2b27d0a1582a3eb754a5a1a3aeaf4738392a916b92',
  },
  {
    name: 'bg_process_list',
    exportName: 'bgProcessList',
    displayName: 'Bg Process List',
    category: 'shell',
    description: "List all background processes and their current status. Use this to: see what background processes are running (dev servers, watchers, builds), find a process ID you forgot, check if a background comm",
    tool: bgProcessList,
    safeByDefault: true,
    implementationHash: 'sha256:dbf189a694c6bacc984eeca085967192249182dbee55ab902ff0bb624227c155',
  },
  {
    name: 'bg_process_output',
    exportName: 'bgProcessOutput',
    displayName: 'Bg Process Output',
    category: 'shell',
    description: "Read output from a background process started with dev_server or bash run_in_background=true. Use this to monitor dev servers, file watchers, build processes, or any background command. For processes ",
    tool: bgProcessOutput,
    safeByDefault: true,
    implementationHash: 'sha256:dee7d75b7c78d99a5b34f30b33095caaa609850a5dbc49e37a69ea24005beb6a',
  },
  {
    name: 'dev_server',
    exportName: 'devServer',
    displayName: 'Dev Server',
    category: 'shell',
    description: "Start a development server or long-running process with automatic log file capture.",
    tool: devServer,
    safeByDefault: false,
    implementationHash: 'sha256:c93531923bcb768358663c62c21c5e0765eee75a1fdcfc1bd73448751bf4d431',
  },
  {
    name: 'web_fetch',
    exportName: 'webFetch',
    displayName: 'Web Fetch',
    category: 'web',
    description: "Fetch and extract content from a URL — works with web pages AND document files (PDF, DOCX, XLSX, PPTX, etc.). Document URLs are automatically detected and converted to markdown text.",
    tool: webFetch,
    safeByDefault: true,
    implementationHash: 'sha256:0ef92315a3da85890950eb2d9659730cd0117d482d3de088b3eff909881c1a9a',
  }
];

/** Get all built-in tools as ToolFunction array */
export function getAllBuiltInTools(): ToolFunction[] {
  return toolRegistry.map((entry) => entry.tool);
}

/** Get full tool registry with metadata */
export function getToolRegistry(): ToolRegistryEntry[] {
  return [...toolRegistry];
}

/** Get tools by category */
export function getToolsByCategory(category: ToolCategory): ToolRegistryEntry[] {
  return toolRegistry.filter((entry) => entry.category === category);
}

/** Get tool by name */
export function getToolByName(name: string): ToolRegistryEntry | undefined {
  return toolRegistry.find((entry) => entry.name === name);
}

/** Get tools that require connector configuration */
export function getToolsRequiringConnector(): ToolRegistryEntry[] {
  return toolRegistry.filter((entry) => entry.requiresConnector);
}

/** Get all unique category names */
export function getToolCategories(): ToolCategory[] {
  return [...new Set(toolRegistry.map((entry) => entry.category))];
}
